//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoachInterest
    {
        public string UserID { get; set; }
        public string Coach { get; set; }
        public string Time { get; set; }
        public string Day { get; set; }
        public string CourseID { get; set; }
        public string Subjects { get; set; }
        public string Interest { get; set; }
    }
}
