
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CoachConnect
{

using System;
    using System.Collections.Generic;
    
public partial class Course
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Course()
    {

        this.UserCourses = new HashSet<UserCourse>();

        this.Sessions = new HashSet<Session>();

    }


    public string CourseID { get; set; }

    public string CourseName { get; set; }

    public bool IsActive { get; set; }

    public string DepartmentID { get; set; }



    public virtual Department Department { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserCourse> UserCourses { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Session> Sessions { get; set; }

}

}
