//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionRoster
    {
        public string SessionRosterID { get; set; }
        public string SessionID { get; set; }
        public string UserCourseID { get; set; }
    
        public virtual Session Session { get; set; }
        public virtual UserCourse UserCourse { get; set; }
    }
}
