
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CoachConnect
{

using System;
    using System.Collections.Generic;
    
public partial class ViewSession
{

    public string Course { get; set; }

    public string Room { get; set; }

    public string Coach { get; set; }

    public bool Active { get; set; }

    public int SessionID { get; set; }

    public string Day { get; set; }

    public string Time { get; set; }

    public bool Full { get; set; }

}

}
